name: Publish a release
run-name: ${{ github.actor }} triggered a release upon new tag

on:
  push:
    tags:
      - "v*.*.*"
jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: echo ${{ github.sha }} > Release.txt
      - name: Testing
        run: cat Release.txt
      - name: Release
        uses: softprops/action-gh-release@v0.1.15
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: Release.txt