name: Publish a release
run-name: ${{ github.actor }} triggered a release upon new tag

on:
  push:
    tags:
      - "v*.*.*"
#      - "ibsim-*.*"

jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Build
        run: |
          ./dist.sh
      - name: Test
        run: |
          test -e ibsim*.tar.gz
      - name: 'Get Previous tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
      - name: Generate Changelog
        run: |
           echo "All component versions are from recent master branch. Full list of changes are below." > ${{ github.workspace }}-CHANGELOG.txt
           git shortlog -n  ${{ steps.previoustag.outputs.tag }}..HEAD >> ${{ github.workspace }}-CHANGELOG.txt
      - name: Release
        uses: softprops/action-gh-release@v0.1.15
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body_path: ${{ github.workspace }}-CHANGELOG.txt
          files: |
            ibsim*.tar.gz